module.exports = {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  safelist: [
    'grid-cols-1',
    'grid-cols-2',
    'grid-cols-3',
    'grid-cols-4',
    'sm:grid-cols-1',
    'sm:grid-cols-2',
    'sm:grid-cols-3',
    'sm:grid-cols-4',
    'md:grid-cols-2',
    'md:grid-cols-4',
    'lg:grid-cols-2',
    'lg:grid-cols-3',
    'lg:grid-cols-12',
    'xl:grid-cols-3',
    'max-w-xs',
    'max-w-md',
    'max-w-2xl',
    'max-w-3xl',
    'max-w-4xl',
    'mx-auto',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
